name: Simple Dual Error Test

on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: finding error
        run: |
          echo "Starting test"
          python3 --version
